### ISSUE TITLE
Fix Github parent child relationship with FlightDataServices/Soapfish

### ISSUE THREAD

**Issue by techdragon** [soapteam/soapfish#110]
At the moment it appears that the majority of work takes place in soapteam/soapfish however since its a fork of FlightDataServices/Soapfish, this breaks a number of useful tools like repository code search.

If its just an accident of history, It would be a good idea to contact GitHub and ask their help in fixing this by either reparenting soapteam/soapfish as not a fork of FlightDataServices/Soapfish or otherwise inverting the parent child fork relationship so that the soapteam/soapfish repo is considered a 'full' repo, not a fork. 

Additionally, it would be good to migrate the issues split across the two repos to whichever becomes the canonical parent, and to close the issue tracking on the whichever repo is intended to be the child.

**Comment by pope1ni** [comment]
This may be a little difficult now. I had originally suggested to @FelixSchwarz that we move the FlightDataServices repository to the soapteam organisation which would have resulted in what you are suggesting, but he preferred at the time to move his personal fork and I was happy to go along with his desires as he had been maintaining it for so long at that time.

Now, I might be able to delete the FlightDataServices repository - although I'd have to get permission to do so from work -  to get it to change the parent, but it sounds like a bit of a [lottery](https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository). It would also mean a loss of historic issues, etc.

**Comment by techdragon** [comment]
@pope1ni I agree it could be a little difficult to clean up. Which is why in the very least it seems the smartest first step would be to contact GitHub as they appear to have some capability to resolve this sort of thing via their support team. 

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact). If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "[About forks](https://help.github.com/articles/about-forks/)."

They definitely have the ability to simply detach this repository from [FlightDataServices/soapfish](https://github.com/FlightDataServices/soapfish) without requiring it to be deleted. Additionally the rest of their commented about keeping forks in the network together, seems to imply they have some ability to manually sort out the parent child fork relationships which might be all that is necessary to _non destructively_ resolve this issue for both repositories.

**Comment by FelixSchwarz** [comment]
I asked github this morning - I'll leave a note here once I got their answer.

**Comment by FelixSchwarz** [comment]
@pope1ni I got a reply from github support and I need an explicit approval from an admin of the FlightDataServices github organization. Assuming you are still ok with fixing the parent/child relation can you please contact me by mail?

**Comment by pope1ni** [comment]
Finally after all this time I've got around to this! Thank you both.
