### ISSUE TITLE
wsdl2py should mangle python keywords and reserved symbols

### ISSUE THREAD

**Issue by trikkegitaar** [soapteam/soapfish#111]
When the WSDL contains element names like "in", then the generated code fails to compile because "in" is not a valid name.
Suggest to prefix or suffix the name.

**Comment by pope1ni** [comment]
I believe that this is already handled using the `keyword` package from the python standard library.
See https://github.com/soapteam/soapfish/blob/638b198/soapfish/utils.py#L156-L185

There may be an edge case that has been missed. Can you attach an example WDSL?

**Comment by trikkegitaar** [comment]
I'm sorry, I got the problem in soapbox and I just noticed this module is deprecated by soapfish. Tried to install the soapfish package, but that gives me the error:

  Could not find a version that satisfies the requirement soapfish (from versions: )
No matching distribution found for soapfish

Tried this with both python27 en python36, same result. Pip was upgraded to 9.0.1. Any hints?

**Comment by pope1ni** [comment]
Sorry - soapfish has not had a release on PyPI yet and you'll have to install it from the master git branch.

Please can you close this issue if the problem no longer exists.

**Comment by trikkegitaar** [comment]
Okay got it. I'm a newbie, so apologies for stupid questions...
