### ISSUE TITLE
wsdl2py throws  AttributeError: 'Part' object has no attribute 'split' error

### ISSUE THREAD

**Issue by Elektroi** [soapteam/soapfish#113]
Hello,
I'm attempting to use the wsdl2py to generate server code from a wsdl file. This is the wsdl [link](https://github.com/knutster/OCPP/blob/master/ocpp_chargepointservice_1.5_final.wsdl)
When I execute:
`python -m soapfish.wsdl2py -s  wsdl/ocpp_chargepointservice_1.5_final.wsdl test.py`

Python throws:

> 
> Traceback (most recent call last):
>   File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "C:\Python27\Lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\Python27\lib\site-packages\soapfish-0.6.0.dev0-py2.7.egg\soapfish\wsdl2py.py", line 153, in <module>
>     sys.exit(main())
>   File "C:\Python27\lib\site-packages\soapfish-0.6.0.dev0-py2.7.egg\soapfish\wsdl2py.py", line 144, in main
>     code = generate_code_from_wsdl(xml, opt.target, opt.use_wsa, cwd=cwd)
>   File "C:\Python27\lib\site-packages\soapfish-0.6.0.dev0-py2.7.egg\soapfish\wsdl2py.py", line 111, in generate_code_from_wsdl
>     use_wsa=use_wsa,
>   File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "C:\Python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Python27\lib\site-packages\soapfish-0.6.0.dev0-py2.7.egg\soapfish\templates\wsdl.jinja2", line 49, in top-level template code
>     SCHEMA = Schema_{{ schema_name(schema_select(definitions.types.schemas, _imh)) }}
>   File "C:\Python27\lib\site-packages\soapfish-0.6.0.dev0-py2.7.egg\soapfish\utils.py", line 80, in schema_select
>     elements = [remove_namespace(x) for x in elements]
>   File "C:\Python27\lib\site-packages\soapfish-0.6.0.dev0-py2.7.egg\soapfish\utils.py", line 45, in remove_namespace
>     return qname.split(':')[-1] if qname else None
> AttributeError: 'Part' object has no attribute 'split'
> 
>

**Comment by pope1ni** [comment]
I've pushed a quick fix that should help you to move past this issue.
