### ISSUE TITLE
Travis: test against different versions of Django (Flask as well?)

### ISSUE THREAD

**Issue by FelixSchwarz** [soapteam/soapfish#70]
We had a couple of bugs that soapfish's Django integration stopped working due to changes in Django. I'd like to ensure that we support at least the latest django for each Python version (which means to use an older Django for Python 2.6 for example). Ideally we could also test the earliest supported method so we can be sure about the versions which should work.

If other frameworks are problematic as well, let's integrate them in the testing matrix.

Pointers:
* [Travis Documentation: "Testing Against Multiple Versions of Dependencies (e.g. Django or Flask)"](https://docs.travis-ci.com/user/languages/python#Testing-Against-Multiple-Versions-of-Dependencies-%28e.g.-Django-or-Flask%29)
* [Blog post with detailed explanation: " Testing Django against Multiple Python Versions with Travis "](http://mjumbewu.blogspot.de/2013/03/testing-django-against-multiple-python.html)
* [Tornado's Travis configuration: using shell conditions](https://github.com/tornadoweb/tornado/blob/master/.travis.yml)
* [example of matrix directive to exclude certain permutations](https://github.com/tomchristie/django-rest-framework/blob/6e6f6f2c7d441a032e8c9a89cd8c37a820eaeaaa/.travis.yml#L24)

**Comment by pope1ni** [comment]
I have been working on a lot of fixes and this one should be solved in my [improvements](https://github.com/flightdataservices/soapfish/tree/improvements) branch by the commit [7c968ac](https://github.com/flightdataservices/soapfish/commit/45c2532). I still have a few more things to finish before I submit a pull request.
