### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by pope1ni** [soapteam/soapfish#89]
I had dropped support for Python 2.6 but it was still required by @FelixSchwarz so it has been restored.

When we decide to go ahead with this we should:
- [x] Revert fixes for Python 2.6 in 641d7e7
- [x] Revert fixes for Python 2.6 in 895cb54
- [x] Revert fixes for Python 2.6 in 6c4abd3
- [x] Revert fixes for Python 2.6 in f7c2dd9
- [x] Revert fixes for Python 2.6 in 364af26
- [x] Make any other changes as required.

**Comment by techdragon** [comment]
@pope1ni @FelixSchwarz - Is 2.6 still needed?

**Comment by FelixSchwarz** [comment]
We still have a couple of Python 2.6 servers with soapfish but these are scheduled for migration to Python 2.7/3.4 anyway so I'm fine with removing 2.6 support if you feel it makes the code simpler.

**Comment by pope1ni** [comment]
Consider it scrapped - 7e41de1.
