### ISSUE TITLE
Refactor handling of location rewriting.

### ISSUE THREAD

**Issue by pope1ni** [soapteam/soapfish#91]
Currently we have multiple ways of handling rewriting of locations in `soapfish.soap.Stub`:

1. Pass the `location` argument when initialising.
2. Pass the `base_url` argument when initialising to extract a *scheme* and *host* from.
3. Alter the `SCHEME` and `HOST` class attributes. (Although this means changing generated code.)

See https://github.com/soapteam/soapfish/blob/737fefc/soapfish/soap.py#L98-L118

We should deprecate or remove `base_url` and allow `location` to be a string or a callable.

If feasible we should also remove `SCHEME` and `HOST` and let people manage rewriting locations entirely within their own callable. This would also remove all the template generation tricks and simplify the code.

The main challenge would be handling the rewriting in the WSDL, but that would benefit from some tidying up to avoid the round-trip through `decode()` and `encode()` on Python 3:

https://github.com/soapteam/soapfish/blob/737fefc/soapfish/soap_dispatch.py#L209-L222

**Comment by FelixSchwarz** [comment]
sounds reasonable to me. Any plans to implement this? :-)

**Comment by pope1ni** [comment]
Yes. The first part is easy, the second - rewriting the WSDL locations - I haven't given much thought to yet.

I've just hacked something ugly in my project for now as I haven't got the time over the next few days.

**Comment by pope1ni** [comment]
I opted not to remove the approach using templates for now because I couldn't think of anything sane...

Closed with the commit of 23701d0. We can reopen if we decide to tidy up the template bit.
